
// Objective-C API for talking to the following Go packages
//
//	github.com/6tail/lunar-go/calendar
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Calendar_FRAMEWORK_H__
#define __Calendar_FRAMEWORK_H__

#include "Calendar.objc.h"
#include "Universe.objc.h"

#endif
