// Objective-C API for talking to github.com/6tail/lunar-go/calendar Go package.
//   gobind -lang=objc github.com/6tail/lunar-go/calendar
//
// File is generated by gobind. Do not edit.

#ifndef __Calendar_H__
#define __Calendar_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class CalendarDaYun;
@class CalendarEightChar;
@class CalendarFoto;
@class CalendarFotoFestival;
@class CalendarFu;
@class CalendarHoliday;
@class CalendarJieQi;
@class CalendarLiuNian;
@class CalendarLiuYue;
@class CalendarLunar;
@class CalendarLunarMonth;
@class CalendarLunarTime;
@class CalendarLunarYear;
@class CalendarNineStar;
@class CalendarShuJiu;
@class CalendarSolar;
@class CalendarSolarHalfYear;
@class CalendarSolarMonth;
@class CalendarSolarSeason;
@class CalendarSolarWeek;
@class CalendarSolarYear;
@class CalendarTao;
@class CalendarTaoFestival;
@class CalendarXiaoYun;
@class CalendarYun;

@interface CalendarDaYun : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(CalendarYun* _Nullable)yun index:(long)index;
- (long)getEndAge;
- (long)getEndYear;
/**
 * 获取干支
 */
- (NSString* _Nonnull)getGanZhi;
- (long)getIndex;
// skipped method DaYun.GetLiuNian with unsupported parameter or return types

// skipped method DaYun.GetLiuNianBy with unsupported parameter or return types

- (CalendarLunar* _Nullable)getLunar;
- (long)getStartAge;
- (long)getStartYear;
// skipped method DaYun.GetXiaoYun with unsupported parameter or return types

// skipped method DaYun.GetXiaoYunBy with unsupported parameter or return types

/**
 * 获取所在旬
 */
- (NSString* _Nonnull)getXun;
/**
 * 获取旬空(空亡)
 */
- (NSString* _Nonnull)getXunKong;
@end

/**
 * 八字
 */
@interface CalendarEightChar : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(CalendarLunar* _Nullable)lunar;
- (NSString* _Nonnull)getDay;
- (NSString* _Nonnull)getDayDiShi;
- (NSString* _Nonnull)getDayGan;
- (long)getDayGanIndex;
// skipped method EightChar.GetDayHideGan with unsupported parameter or return types

- (NSString* _Nonnull)getDayNaYin;
- (NSString* _Nonnull)getDayShiShenGan;
// skipped method EightChar.GetDayShiShenZhi with unsupported parameter or return types

- (NSString* _Nonnull)getDayWuXing;
/**
 * 获取日柱所在旬
 */
- (NSString* _Nonnull)getDayXun;
/**
 * 获取日柱旬空(空亡)
 */
- (NSString* _Nonnull)getDayXunKong;
- (NSString* _Nonnull)getDayZhi;
- (long)getDayZhiIndex;
- (CalendarLunar* _Nullable)getLunar;
- (NSString* _Nonnull)getMingGong;
- (NSString* _Nonnull)getMingGongNaYin;
- (NSString* _Nonnull)getMonth;
- (NSString* _Nonnull)getMonthDiShi;
- (NSString* _Nonnull)getMonthGan;
// skipped method EightChar.GetMonthHideGan with unsupported parameter or return types

- (NSString* _Nonnull)getMonthNaYin;
- (NSString* _Nonnull)getMonthShiShenGan;
// skipped method EightChar.GetMonthShiShenZhi with unsupported parameter or return types

- (NSString* _Nonnull)getMonthWuXing;
/**
 * 获取月柱所在旬
 */
- (NSString* _Nonnull)getMonthXun;
/**
 * 获取月柱旬空(空亡)
 */
- (NSString* _Nonnull)getMonthXunKong;
- (NSString* _Nonnull)getMonthZhi;
- (long)getSect;
- (NSString* _Nonnull)getShenGong;
- (NSString* _Nonnull)getShenGongNaYin;
- (NSString* _Nonnull)getTaiYuan;
- (NSString* _Nonnull)getTaiYuanNaYin;
- (NSString* _Nonnull)getTime;
- (NSString* _Nonnull)getTimeDiShi;
- (NSString* _Nonnull)getTimeGan;
// skipped method EightChar.GetTimeHideGan with unsupported parameter or return types

- (NSString* _Nonnull)getTimeNaYin;
- (NSString* _Nonnull)getTimeShiShenGan;
// skipped method EightChar.GetTimeShiShenZhi with unsupported parameter or return types

- (NSString* _Nonnull)getTimeWuXing;
/**
 * 获取时柱所在旬
 */
- (NSString* _Nonnull)getTimeXun;
/**
 * 获取时柱旬空(空亡)
 */
- (NSString* _Nonnull)getTimeXunKong;
- (NSString* _Nonnull)getTimeZhi;
- (NSString* _Nonnull)getYear;
- (NSString* _Nonnull)getYearDiShi;
- (NSString* _Nonnull)getYearGan;
// skipped method EightChar.GetYearHideGan with unsupported parameter or return types

- (NSString* _Nonnull)getYearNaYin;
- (NSString* _Nonnull)getYearShiShenGan;
// skipped method EightChar.GetYearShiShenZhi with unsupported parameter or return types

- (NSString* _Nonnull)getYearWuXing;
/**
 * 获取年柱所在旬
 */
- (NSString* _Nonnull)getYearXun;
/**
 * 获取年柱旬空(空亡)
 */
- (NSString* _Nonnull)getYearXunKong;
- (NSString* _Nonnull)getYearZhi;
/**
 * 获取运
 */
- (CalendarYun* _Nullable)getYun:(long)gender;
- (void)setSect:(long)sect;
- (NSString* _Nonnull)string;
@end

/**
 * 佛历
 */
@interface CalendarFoto : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)year month:(long)month day:(long)day hour:(long)hour minute:(long)minute second:(long)second;
- (nullable instancetype)initFromLunar:(CalendarLunar* _Nullable)lunar;
- (nullable instancetype)initFromYmd:(long)year month:(long)month day:(long)day;
- (NSString* _Nonnull)getAnimal;
- (long)getDay;
- (NSString* _Nonnull)getDayInChinese;
// skipped method Foto.GetFestivals with unsupported parameter or return types

- (NSString* _Nonnull)getGong;
- (CalendarLunar* _Nullable)getLunar;
- (long)getMonth;
- (NSString* _Nonnull)getMonthInChinese;
- (NSString* _Nonnull)getShou;
- (NSString* _Nonnull)getXiu;
- (NSString* _Nonnull)getXiuLuck;
- (NSString* _Nonnull)getXiuSong;
- (long)getYear;
- (NSString* _Nonnull)getYearInChinese;
- (NSString* _Nonnull)getZheng;
- (BOOL)isDayYangGong;
- (BOOL)isDayZhaiGuanYin;
- (BOOL)isDayZhaiShuoWang;
- (BOOL)isDayZhaiSix;
- (BOOL)isDayZhaiTen;
- (BOOL)isMonthZhai;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
- (NSString* _Nonnull)toString;
@end

/**
 * 佛历因果犯忌
 */
@interface CalendarFotoFestival : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)name result:(NSString* _Nullable)result everyMonth:(BOOL)everyMonth remark:(NSString* _Nullable)remark;
- (NSString* _Nonnull)getName;
- (NSString* _Nonnull)getRemark;
- (NSString* _Nonnull)getResult;
- (BOOL)isEveryMonth;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
- (NSString* _Nonnull)toString;
@end

/**
 * 伏
 */
@interface CalendarFu : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)name index:(long)index;
- (long)getIndex;
- (NSString* _Nonnull)getName;
- (void)setIndex:(long)index;
- (void)setName:(NSString* _Nullable)name;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
- (NSString* _Nonnull)toString;
@end

/**
 * 节假日
 */
@interface CalendarHoliday : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)day name:(NSString* _Nullable)name work:(BOOL)work target:(NSString* _Nullable)target;
- (NSString* _Nonnull)getDay;
- (NSString* _Nonnull)getName;
- (NSString* _Nonnull)getTarget;
- (BOOL)isWork;
- (void)setDay:(NSString* _Nullable)day;
- (void)setName:(NSString* _Nullable)name;
- (void)setTarget:(NSString* _Nullable)target;
- (void)setWork:(BOOL)work;
- (NSString* _Nonnull)string;
@end

/**
 * 节气
 */
@interface CalendarJieQi : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)name solar:(CalendarSolar* _Nullable)solar;
/**
 * 获取名称
 */
- (NSString* _Nonnull)getName;
/**
 * 获取阳历日期
 */
- (CalendarSolar* _Nullable)getSolar;
/**
 * 是否节令
 */
- (BOOL)isJie;
/**
 * 是否气令
 */
- (BOOL)isQi;
/**
 * 设置名称
 */
- (void)setName:(NSString* _Nullable)name;
/**
 * 设置阳历日期
 */
- (void)setSolar:(CalendarSolar* _Nullable)solar;
- (NSString* _Nonnull)string;
@end

/**
 * 流年
 */
@interface CalendarLiuNian : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(CalendarDaYun* _Nullable)daYun index:(long)index;
- (long)getAge;
/**
 * 获取干支
 */
- (NSString* _Nonnull)getGanZhi;
- (long)getIndex;
// skipped method LiuNian.GetLiuYue with unsupported parameter or return types

/**
 * 获取所在旬
 */
- (NSString* _Nonnull)getXun;
/**
 * 获取旬空(空亡)
 */
- (NSString* _Nonnull)getXunKong;
- (long)getYear;
@end

/**
 * 流月
 */
@interface CalendarLiuYue : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(CalendarLiuNian* _Nullable)liuNian index:(long)index;
/**
 * 获取干支
<p>
《五虎遁》
甲己之年丙作首，
乙庚之年戊为头，
丙辛之年寻庚上，
丁壬壬寅顺水流，
若问戊癸何处走，
甲寅之上好追求。
 */
- (NSString* _Nonnull)getGanZhi;
- (long)getIndex;
/**
 * 获取中文的月
 */
- (NSString* _Nonnull)getMonthInChinese;
/**
 * 获取所在旬
 */
- (NSString* _Nonnull)getXun;
/**
 * 获取旬空(空亡)
 */
- (NSString* _Nonnull)getXunKong;
@end

/**
 * 阴历
 */
@interface CalendarLunar : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)lunarYear lunarMonth:(long)lunarMonth lunarDay:(long)lunarDay hour:(long)hour minute:(long)minute second:(long)second;
// skipped constructor Lunar.NewLunarFromDate with unsupported parameter or return types

- (nullable instancetype)initFromSolarYmd:(long)year month:(long)month day:(long)day hour:(long)hour minute:(long)minute second:(long)second;
- (nullable instancetype)initFromYmd:(long)lunarYear lunarMonth:(long)lunarMonth lunarDay:(long)lunarDay;
- (NSString* _Nonnull)getAnimal;
// skipped method Lunar.GetBaZi with unsupported parameter or return types

// skipped method Lunar.GetBaZiNaYin with unsupported parameter or return types

// skipped method Lunar.GetBaZiShiShenDayZhi with unsupported parameter or return types

// skipped method Lunar.GetBaZiShiShenGan with unsupported parameter or return types

// skipped method Lunar.GetBaZiShiShenMonthZhi with unsupported parameter or return types

// skipped method Lunar.GetBaZiShiShenTimeZhi with unsupported parameter or return types

// skipped method Lunar.GetBaZiShiShenYearZhi with unsupported parameter or return types

// skipped method Lunar.GetBaZiShiShenZhi with unsupported parameter or return types

// skipped method Lunar.GetBaZiWuXing with unsupported parameter or return types

/**
 * @Deprecated: 该方法已废弃，请使用GetDayChong
 */
- (NSString* _Nonnull)getChong;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayChongDesc
 */
- (NSString* _Nonnull)getChongDesc;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayChongGan
 */
- (NSString* _Nonnull)getChongGan;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayChongGanTie
 */
- (NSString* _Nonnull)getChongGanTie;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayChongShengXiao
 */
- (NSString* _Nonnull)getChongShengXiao;
/**
 * 获取当天节令对象，如果无节令，返回nil
 */
- (CalendarJieQi* _Nullable)getCurrentJie;
/**
 * 获取当天节气对象，如果无节气，返回nil
 */
- (CalendarJieQi* _Nullable)getCurrentJieQi;
/**
 * 获取当天气令对象，如果无气令，返回nil
 */
- (CalendarJieQi* _Nullable)getCurrentQi;
- (long)getDay;
- (NSString* _Nonnull)getDayChong;
- (NSString* _Nonnull)getDayChongDesc;
- (NSString* _Nonnull)getDayChongGan;
- (NSString* _Nonnull)getDayChongGanTie;
- (NSString* _Nonnull)getDayChongShengXiao;
- (NSString* _Nonnull)getDayGan;
- (NSString* _Nonnull)getDayGanExact;
- (NSString* _Nonnull)getDayGanExact2;
- (long)getDayGanIndex;
- (long)getDayGanIndexExact;
- (long)getDayGanIndexExact2;
- (NSString* _Nonnull)getDayInChinese;
- (NSString* _Nonnull)getDayInGanZhi;
- (NSString* _Nonnull)getDayInGanZhiExact;
- (NSString* _Nonnull)getDayInGanZhiExact2;
// skipped method Lunar.GetDayJi with unsupported parameter or return types

// skipped method Lunar.GetDayJiShen with unsupported parameter or return types

- (NSString* _Nonnull)getDayJiShenStrings;
- (NSString* _Nonnull)getDayJiStrings;
/**
 * 获取日禄
 */
- (NSString* _Nonnull)getDayLu;
- (NSString* _Nonnull)getDayNaYin;
- (CalendarNineStar* _Nullable)getDayNineStar;
- (NSString* _Nonnull)getDayPositionCai;
- (NSString* _Nonnull)getDayPositionCaiDesc;
- (NSString* _Nonnull)getDayPositionFu;
- (NSString* _Nonnull)getDayPositionFuBySect:(long)sect;
- (NSString* _Nonnull)getDayPositionFuDesc;
- (NSString* _Nonnull)getDayPositionFuDescBySect:(long)sect;
- (NSString* _Nonnull)getDayPositionTai;
- (NSString* _Nonnull)getDayPositionXi;
- (NSString* _Nonnull)getDayPositionXiDesc;
- (NSString* _Nonnull)getDayPositionYangGui;
- (NSString* _Nonnull)getDayPositionYangGuiDesc;
- (NSString* _Nonnull)getDayPositionYinGui;
- (NSString* _Nonnull)getDayPositionYinGuiDesc;
- (NSString* _Nonnull)getDaySha;
- (NSString* _Nonnull)getDayShengXiao;
- (NSString* _Nonnull)getDayTianShen;
- (NSString* _Nonnull)getDayTianShenLuck;
- (NSString* _Nonnull)getDayTianShenType;
// skipped method Lunar.GetDayXiongSha with unsupported parameter or return types

- (NSString* _Nonnull)getDayXiongShaStrings;
/**
 * 获取日所在旬（以节交接当天起算）
 */
- (NSString* _Nonnull)getDayXun;
/**
 * 获取日所在旬（晚子时日柱算明天）
 */
- (NSString* _Nonnull)getDayXunExact;
/**
 * 获取日所在旬（晚子时日柱算当天）
 */
- (NSString* _Nonnull)getDayXunExact2;
/**
 * 获取值日空亡
 */
- (NSString* _Nonnull)getDayXunKong;
/**
 * 获取值日空亡（晚子时日柱算明天）
 */
- (NSString* _Nonnull)getDayXunKongExact;
/**
 * 获取值日空亡（晚子时日柱算当天）
 */
- (NSString* _Nonnull)getDayXunKongExact2;
// skipped method Lunar.GetDayYi with unsupported parameter or return types

- (NSString* _Nonnull)getDayYiStrings;
- (NSString* _Nonnull)getDayZhi;
- (NSString* _Nonnull)getDayZhiExact;
- (NSString* _Nonnull)getDayZhiExact2;
- (long)getDayZhiIndex;
- (long)getDayZhiIndexExact;
- (long)getDayZhiIndexExact2;
- (CalendarEightChar* _Nullable)getEightChar;
// skipped method Lunar.GetFestivals with unsupported parameter or return types

/**
 * 获取佛历
 */
- (CalendarFoto* _Nullable)getFoto;
/**
 * 获取三伏，如果不是三伏天，返回nil
 */
- (CalendarFu* _Nullable)getFu;
/**
 * @Deprecated: 该方法已废弃，请使用GetYearGan
 */
- (NSString* _Nonnull)getGan;
- (NSString* _Nonnull)getGong;
- (long)getHour;
- (NSString* _Nonnull)getJie;
/**
 * 获取节气名称，如果无节气，返回空字符串
 */
- (NSString* _Nonnull)getJieQi;
// skipped method Lunar.GetJieQiList with unsupported parameter or return types

// skipped method Lunar.GetJieQiTable with unsupported parameter or return types

/**
 * 获取六曜
 */
- (NSString* _Nonnull)getLiuYao;
- (long)getMinute;
- (long)getMonth;
- (NSString* _Nonnull)getMonthGan;
- (NSString* _Nonnull)getMonthGanExact;
- (long)getMonthGanIndex;
- (long)getMonthGanIndexExact;
- (NSString* _Nonnull)getMonthInChinese;
- (NSString* _Nonnull)getMonthInGanZhi;
- (NSString* _Nonnull)getMonthInGanZhiExact;
- (NSString* _Nonnull)getMonthNaYin;
- (CalendarNineStar* _Nullable)getMonthNineStar;
- (NSString* _Nonnull)getMonthPositionTai;
- (NSString* _Nonnull)getMonthShengXiao;
/**
 * 获取月所在旬（以节交接当天起算）
 */
- (NSString* _Nonnull)getMonthXun;
/**
 * 获取月所在旬（以节交接时刻起算）
 */
- (NSString* _Nonnull)getMonthXunExact;
/**
 * 获取值月空亡（以节交接当天起算）
 */
- (NSString* _Nonnull)getMonthXunKong;
/**
 * 获取值月空亡（以节交接时刻起算）
 */
- (NSString* _Nonnull)getMonthXunKongExact;
- (NSString* _Nonnull)getMonthZhi;
- (NSString* _Nonnull)getMonthZhiExact;
- (long)getMonthZhiIndex;
- (long)getMonthZhiIndexExact;
/**
 * 获取下一节（顺推的第一个节）
 */
- (CalendarJieQi* _Nullable)getNextJie;
/**
 * 获取下一节气（顺推的第一个节气）
 */
- (CalendarJieQi* _Nullable)getNextJieQi;
/**
 * 获取下一气令（顺推的第一个气令）
 */
- (CalendarJieQi* _Nullable)getNextQi;
// skipped method Lunar.GetOtherFestivals with unsupported parameter or return types

- (NSString* _Nonnull)getPengZuGan;
- (NSString* _Nonnull)getPengZuZhi;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionCai
 */
- (NSString* _Nonnull)getPositionCai;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionCaiDesc
 */
- (NSString* _Nonnull)getPositionCaiDesc;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionFu
 */
- (NSString* _Nonnull)getPositionFu;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionFuDesc
 */
- (NSString* _Nonnull)getPositionFuDesc;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionXi
 */
- (NSString* _Nonnull)getPositionXi;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionXiDesc
 */
- (NSString* _Nonnull)getPositionXiDesc;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionYangGui
 */
- (NSString* _Nonnull)getPositionYangGui;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionYangGuiDesc
 */
- (NSString* _Nonnull)getPositionYangGuiDesc;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionYinGui
 */
- (NSString* _Nonnull)getPositionYinGui;
/**
 * @Deprecated: 该方法已废弃，请使用GetDayPositionYinGuiDesc
 */
- (NSString* _Nonnull)getPositionYinGuiDesc;
/**
 * 获取上一节（逆推的第一个节）
 */
- (CalendarJieQi* _Nullable)getPrevJie;
/**
 * 获取上一节气（逆推的第一个节气）
 */
- (CalendarJieQi* _Nullable)getPrevJieQi;
/**
 * 获取上一气令（逆推的第一个气令）
 */
- (CalendarJieQi* _Nullable)getPrevQi;
- (NSString* _Nonnull)getQi;
- (NSString* _Nonnull)getSeason;
- (long)getSecond;
/**
 * @Deprecated: 该方法已废弃，请使用GetDaySha
 */
- (NSString* _Nonnull)getSha;
/**
 * @Deprecated: 该方法已废弃，请使用GetYearShengXiao
 */
- (NSString* _Nonnull)getShengxiao;
- (NSString* _Nonnull)getShou;
/**
 * 获取数九，如果不是数九天，返回nil
 */
- (CalendarShuJiu* _Nullable)getShuJiu;
- (CalendarSolar* _Nullable)getSolar;
/**
 * 获取道历
 */
- (CalendarTao* _Nullable)getTao;
/**
 * 获取时辰
 */
- (CalendarLunarTime* _Nullable)getTime;
- (NSString* _Nonnull)getTimeChong;
- (NSString* _Nonnull)getTimeChongDesc;
- (NSString* _Nonnull)getTimeChongGan;
- (NSString* _Nonnull)getTimeChongGanTie;
- (NSString* _Nonnull)getTimeChongShengXiao;
- (NSString* _Nonnull)getTimeGan;
- (long)getTimeGanIndex;
- (NSString* _Nonnull)getTimeInGanZhi;
// skipped method Lunar.GetTimeJi with unsupported parameter or return types

- (NSString* _Nonnull)getTimeJiStrings;
- (NSString* _Nonnull)getTimeNaYin;
- (CalendarNineStar* _Nullable)getTimeNineStar;
- (NSString* _Nonnull)getTimePositionCai;
- (NSString* _Nonnull)getTimePositionCaiDesc;
- (NSString* _Nonnull)getTimePositionFu;
- (NSString* _Nonnull)getTimePositionFuDesc;
- (NSString* _Nonnull)getTimePositionXi;
- (NSString* _Nonnull)getTimePositionXiDesc;
- (NSString* _Nonnull)getTimePositionYangGui;
- (NSString* _Nonnull)getTimePositionYangGuiDesc;
- (NSString* _Nonnull)getTimePositionYinGui;
- (NSString* _Nonnull)getTimePositionYinGuiDesc;
- (NSString* _Nonnull)getTimeSha;
- (NSString* _Nonnull)getTimeShengXiao;
- (NSString* _Nonnull)getTimeTianShen;
- (NSString* _Nonnull)getTimeTianShenLuck;
- (NSString* _Nonnull)getTimeTianShenType;
/**
 * 获取时辰所在旬
 */
- (NSString* _Nonnull)getTimeXun;
/**
 * 获取值时空亡
 */
- (NSString* _Nonnull)getTimeXunKong;
// skipped method Lunar.GetTimeYi with unsupported parameter or return types

- (NSString* _Nonnull)getTimeYiStrings;
- (NSString* _Nonnull)getTimeZhi;
- (long)getTimeZhiIndex;
// skipped method Lunar.GetTimes with unsupported parameter or return types

- (long)getWeek;
- (NSString* _Nonnull)getWeekInChinese;
/**
 * 获取物候
 */
- (NSString* _Nonnull)getWuHou;
- (NSString* _Nonnull)getXiu;
- (NSString* _Nonnull)getXiuLuck;
- (NSString* _Nonnull)getXiuSong;
- (long)getYear;
- (NSString* _Nonnull)getYearGan;
- (NSString* _Nonnull)getYearGanByLiChun;
- (NSString* _Nonnull)getYearGanExact;
- (long)getYearGanIndex;
- (long)getYearGanIndexByLiChun;
- (long)getYearGanIndexExact;
- (NSString* _Nonnull)getYearInChinese;
- (NSString* _Nonnull)getYearInGanZhi;
- (NSString* _Nonnull)getYearInGanZhiByLiChun;
- (NSString* _Nonnull)getYearInGanZhiExact;
- (NSString* _Nonnull)getYearNaYin;
- (CalendarNineStar* _Nullable)getYearNineStar;
- (NSString* _Nonnull)getYearShengXiao;
- (NSString* _Nonnull)getYearShengXiaoByLiChun;
- (NSString* _Nonnull)getYearShengXiaoExact;
/**
 * 获取年所在旬（以正月初一作为新年的开始）
 */
- (NSString* _Nonnull)getYearXun;
/**
 * 获取年所在旬（以立春当天作为新年的开始）
 */
- (NSString* _Nonnull)getYearXunByLiChun;
/**
 * 获取年所在旬（以立春交接时刻作为新年的开始）
 */
- (NSString* _Nonnull)getYearXunExact;
/**
 * 获取值年空亡（以正月初一作为新年的开始）
 */
- (NSString* _Nonnull)getYearXunKong;
/**
 * 获取值年空亡（以立春当天作为新年的开始）
 */
- (NSString* _Nonnull)getYearXunKongByLiChun;
/**
 * 获取值年空亡（以立春交接时刻作为新年的开始）
 */
- (NSString* _Nonnull)getYearXunKongExact;
- (NSString* _Nonnull)getYearZhi;
- (NSString* _Nonnull)getYearZhiByLiChun;
- (NSString* _Nonnull)getYearZhiExact;
- (long)getYearZhiIndex;
- (long)getYearZhiIndexByLiChun;
- (long)getYearZhiIndexExact;
- (NSString* _Nonnull)getYueXiang;
- (NSString* _Nonnull)getZheng;
/**
 * @Deprecated: 该方法已废弃，请使用GetYearZhi
 */
- (NSString* _Nonnull)getZhi;
- (NSString* _Nonnull)getZhiXing;
/**
 * 获取往后推几天的农历日期，如果要往前推，则天数用负数
 */
- (CalendarLunar* _Nullable)next:(long)days;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
@end

/**
 * 阴历月
 */
@interface CalendarLunarMonth : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)lunarYear lunarMonth:(long)lunarMonth dayCount:(long)dayCount firstJulianDay:(double)firstJulianDay;
- (nullable instancetype)initFromYm:(long)lunarYear lunarMonth:(long)lunarMonth;
- (long)getDayCount;
- (double)getFirstJulianDay;
- (long)getMonth;
- (long)getYear;
- (BOOL)isLeap;
- (NSString* _Nonnull)string;
@end

/**
 * 时辰
 */
@interface CalendarLunarTime : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)lunarYear lunarMonth:(long)lunarMonth lunarDay:(long)lunarDay hour:(long)hour minute:(long)minute second:(long)second;
- (NSString* _Nonnull)getChong;
- (NSString* _Nonnull)getChongDesc;
- (NSString* _Nonnull)getChongGan;
- (NSString* _Nonnull)getChongGanTie;
- (NSString* _Nonnull)getChongShengXiao;
- (NSString* _Nonnull)getGan;
- (long)getGanIndex;
- (NSString* _Nonnull)getGanZhi;
// skipped method LunarTime.GetJi with unsupported parameter or return types

/**
 * 获取当前时辰的最晚时分
 */
- (NSString* _Nonnull)getMaxHm;
/**
 * 获取当前时辰的最早时分
 */
- (NSString* _Nonnull)getMinHm;
- (NSString* _Nonnull)getNaYin;
- (CalendarNineStar* _Nullable)getNineStar;
- (NSString* _Nonnull)getPositionCai;
- (NSString* _Nonnull)getPositionCaiDesc;
- (NSString* _Nonnull)getPositionFu;
- (NSString* _Nonnull)getPositionFuBySect:(long)sect;
- (NSString* _Nonnull)getPositionFuDesc;
- (NSString* _Nonnull)getPositionFuDescBySect:(long)sect;
- (NSString* _Nonnull)getPositionXi;
- (NSString* _Nonnull)getPositionXiDesc;
- (NSString* _Nonnull)getPositionYangGui;
- (NSString* _Nonnull)getPositionYangGuiDesc;
- (NSString* _Nonnull)getPositionYinGui;
- (NSString* _Nonnull)getPositionYinGuiDesc;
- (NSString* _Nonnull)getSha;
- (NSString* _Nonnull)getShengXiao;
- (NSString* _Nonnull)getTianShen;
- (NSString* _Nonnull)getTianShenLuck;
- (NSString* _Nonnull)getTianShenType;
/**
 * 获取时辰所在旬
 */
- (NSString* _Nonnull)getXun;
/**
 * 获取值时空亡
 */
- (NSString* _Nonnull)getXunKong;
// skipped method LunarTime.GetYi with unsupported parameter or return types

- (NSString* _Nonnull)getZhi;
- (long)getZhiIndex;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toString;
@end

/**
 * 阴历年
 */
@interface CalendarLunarYear : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)lunarYear;
- (NSString* _Nonnull)getDeJin;
- (NSString* _Nonnull)getFenBing;
- (NSString* _Nonnull)getGengTian;
// skipped method LunarYear.GetJieQiJulianDays with unsupported parameter or return types

- (CalendarLunarMonth* _Nullable)getMonth:(long)lunarMonth;
// skipped method LunarYear.GetMonths with unsupported parameter or return types

- (NSString* _Nonnull)getMonthsInString;
- (long)getYear;
- (NSString* _Nonnull)getZhiShui;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
@end

/**
 * 九星
 */
@interface CalendarNineStar : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)index;
- (NSString* _Nonnull)getBaMenInQiMen;
- (NSString* _Nonnull)getColor;
- (long)getIndex;
- (NSString* _Nonnull)getLuckInQiMen;
- (NSString* _Nonnull)getLuckInXuanKong;
- (NSString* _Nonnull)getNameInBeiDou;
- (NSString* _Nonnull)getNameInQiMen;
- (NSString* _Nonnull)getNameInTaiYi;
- (NSString* _Nonnull)getNameInXuanKong;
- (NSString* _Nonnull)getNumber;
- (NSString* _Nonnull)getPosition;
- (NSString* _Nonnull)getPositionDesc;
- (NSString* _Nonnull)getSongInTaiYi;
- (NSString* _Nonnull)getTypeInTaiYi;
- (NSString* _Nonnull)getWuXing;
- (NSString* _Nonnull)getYinYangInQiMen;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
@end

/**
 * 数九
 */
@interface CalendarShuJiu : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)name index:(long)index;
- (long)getIndex;
- (NSString* _Nonnull)getName;
- (void)setIndex:(long)index;
- (void)setName:(NSString* _Nullable)name;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
- (NSString* _Nonnull)toString;
@end

/**
 * 阳历
 */
@interface CalendarSolar : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)year month:(long)month day:(long)day hour:(long)hour minute:(long)minute second:(long)second;
// skipped constructor Solar.NewSolarFromDate with unsupported parameter or return types

- (nullable instancetype)initFromJulianDay:(double)julianDay;
- (nullable instancetype)initFromYmd:(long)year month:(long)month day:(long)day;
// skipped method Solar.GetCalendar with unsupported parameter or return types

- (long)getDay;
// skipped method Solar.GetFestivals with unsupported parameter or return types

- (long)getHour;
- (double)getJulianDay;
- (CalendarLunar* _Nullable)getLunar;
- (long)getMinute;
- (long)getMonth;
// skipped method Solar.GetOtherFestivals with unsupported parameter or return types

- (long)getSecond;
- (long)getWeek;
- (NSString* _Nonnull)getWeekInChinese;
- (NSString* _Nonnull)getXingZuo;
/**
 * @Deprecated: 该方法已废弃，请使用GetXingZuo
 */
- (NSString* _Nonnull)getXingzuo;
- (long)getYear;
- (BOOL)isLeapYear;
- (CalendarSolar* _Nullable)next:(long)days;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
- (NSString* _Nonnull)toYmd;
- (NSString* _Nonnull)toYmdHms;
@end

/**
 * 阳历半年
 */
@interface CalendarSolarHalfYear : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
// skipped constructor SolarHalfYear.NewSolarHalfYearFromDate with unsupported parameter or return types

- (nullable instancetype)initFromYm:(long)year month:(long)month;
- (long)getIndex;
- (long)getMonth;
// skipped method SolarHalfYear.GetMonths with unsupported parameter or return types

- (long)getYear;
- (CalendarSolarHalfYear* _Nullable)next:(long)halfYears;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
@end

/**
 * 阳历月
 */
@interface CalendarSolarMonth : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
// skipped constructor SolarMonth.NewSolarMonthFromDate with unsupported parameter or return types

- (nullable instancetype)initFromYm:(long)year month:(long)month;
// skipped method SolarMonth.GetDays with unsupported parameter or return types

- (long)getMonth;
- (long)getYear;
- (CalendarSolarMonth* _Nullable)next:(long)months;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
@end

/**
 * 阳历季度
 */
@interface CalendarSolarSeason : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
// skipped constructor SolarSeason.NewSolarSeasonFromDate with unsupported parameter or return types

- (nullable instancetype)initFromYm:(long)year month:(long)month;
- (long)getIndex;
- (long)getMonth;
// skipped method SolarSeason.GetMonths with unsupported parameter or return types

- (long)getYear;
- (CalendarSolarSeason* _Nullable)next:(long)seasons;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
@end

/**
 * 阳历周
 */
@interface CalendarSolarWeek : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)start;
// skipped constructor SolarWeek.NewSolarWeekFromDate with unsupported parameter or return types

- (nullable instancetype)initFromYmd:(long)year month:(long)month day:(long)day start:(long)start;
- (long)getDay;
// skipped method SolarWeek.GetDays with unsupported parameter or return types

// skipped method SolarWeek.GetDaysInMonth with unsupported parameter or return types

- (CalendarSolar* _Nullable)getFirstDay;
- (CalendarSolar* _Nullable)getFirstDayInMonth;
- (long)getIndex;
- (long)getMonth;
- (long)getYear;
- (CalendarSolarWeek* _Nullable)next:(long)weeks separateMonth:(BOOL)separateMonth;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
@end

/**
 * 阳历年
 */
@interface CalendarSolarYear : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init;
// skipped constructor SolarYear.NewSolarYearFromDate with unsupported parameter or return types

- (nullable instancetype)initFromYear:(long)year;
// skipped method SolarYear.GetMonths with unsupported parameter or return types

- (long)getYear;
- (CalendarSolarYear* _Nullable)next:(long)years;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
@end

/**
 * 道历
 */
@interface CalendarTao : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)year month:(long)month day:(long)day hour:(long)hour minute:(long)minute second:(long)second;
- (nullable instancetype)initFromLunar:(CalendarLunar* _Nullable)lunar;
- (nullable instancetype)initFromYmd:(long)year month:(long)month day:(long)day;
- (long)getDay;
- (NSString* _Nonnull)getDayInChinese;
// skipped method Tao.GetFestivals with unsupported parameter or return types

- (CalendarLunar* _Nullable)getLunar;
- (long)getMonth;
- (NSString* _Nonnull)getMonthInChinese;
- (long)getYear;
- (NSString* _Nonnull)getYearInChinese;
- (BOOL)isDayBaHui;
- (BOOL)isDayBaJie;
- (BOOL)isDaySanHui;
- (BOOL)isDaySanYuan;
- (BOOL)isDayWuLa;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
- (NSString* _Nonnull)toString;
@end

/**
 * 道历节日
 */
@interface CalendarTaoFestival : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(NSString* _Nullable)name remark:(NSString* _Nullable)remark;
- (NSString* _Nonnull)getName;
- (NSString* _Nonnull)getRemark;
- (NSString* _Nonnull)string;
- (NSString* _Nonnull)toFullString;
- (NSString* _Nonnull)toString;
@end

/**
 * 小运
 */
@interface CalendarXiaoYun : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(CalendarDaYun* _Nullable)daYun index:(long)index forward:(BOOL)forward;
- (long)getAge;
/**
 * 获取干支
 */
- (NSString* _Nonnull)getGanZhi;
- (long)getIndex;
/**
 * 获取所在旬
 */
- (NSString* _Nonnull)getXun;
/**
 * 获取旬空(空亡)
 */
- (NSString* _Nonnull)getXunKong;
- (long)getYear;
@end

@interface CalendarYun : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(CalendarEightChar* _Nullable)eightChar gender:(long)gender;
// skipped method Yun.GetDaYun with unsupported parameter or return types

// skipped method Yun.GetDaYunBy with unsupported parameter or return types

/**
 * 获取性别
 */
- (long)getGender;
- (CalendarLunar* _Nullable)getLunar;
/**
 * 获取起运天数
 */
- (long)getStartDay;
/**
 * 获取起运月数
 */
- (long)getStartMonth;
/**
 * 获取起运的阳历日期
 */
- (CalendarSolar* _Nullable)getStartSolar;
/**
 * 获取起运年数
 */
- (long)getStartYear;
/**
 * 是否顺推
 */
- (BOOL)isForward;
@end

FOUNDATION_EXPORT const int64_t CalendarJ2000;
FOUNDATION_EXPORT const int64_t CalendarMONTH_IN_HALF_YEAR;
FOUNDATION_EXPORT const int64_t CalendarMONTH_IN_SEASON;
FOUNDATION_EXPORT const int64_t CalendarMONTH_IN_YEAR;

@interface Calendar : NSObject
// skipped variable BA_MEN_QI_MEN with unsupported type: []string

+ (long) birtH_YEAR;
+ (void) setBIRTH_YEAR:(long)v;

// skipped variable CACHE with unsupported type: map[int]*github.com/6tail/lunar-go/calendar.LunarYear

// skipped variable CHANG_SHENG with unsupported type: []string

// skipped variable COLOR with unsupported type: []string

+ (long) deaD_YEAR;
+ (void) setDEAD_YEAR:(long)v;

// skipped variable JIE_QI with unsupported type: []string

// skipped variable JIE_QI_IN_USE with unsupported type: []string

// skipped variable LEAP with unsupported type: map[int]int

// skipped variable LEAP_11 with unsupported type: []int

// skipped variable LEAP_12 with unsupported type: []int

// skipped variable LUCK_QI_MEN with unsupported type: []string

// skipped variable LUCK_XUAN_KONG with unsupported type: []string

// skipped variable MONTH_ZHI with unsupported type: []string

// skipped variable NAMES with unsupported type: []string

// skipped variable NAME_BEI_DOU with unsupported type: []string

// skipped variable NAME_QI_MEN with unsupported type: []string

// skipped variable NAME_TAI_YI with unsupported type: []string

// skipped variable NAME_XUAN_KONG with unsupported type: []string

// skipped variable NUMBER with unsupported type: []string

// skipped variable POSITION with unsupported type: []string

// skipped variable SONG_TAI_YI with unsupported type: []string

// skipped variable TYPE_TAI_YI with unsupported type: []string

// skipped variable WU_XING with unsupported type: []string

// skipped variable YIN_YANG_QI_MEN with unsupported type: []string

@end

// skipped function Fix with unsupported parameter or return types


FOUNDATION_EXPORT CalendarHoliday* _Nullable CalendarGetHoliday(NSString* _Nullable ymd);

FOUNDATION_EXPORT CalendarHoliday* _Nullable CalendarGetHolidayByYmd(long year, long month, long day);

// skipped function GetHolidays with unsupported parameter or return types


// skipped function GetHolidaysByTarget with unsupported parameter or return types


// skipped function GetHolidaysByTargetYmd with unsupported parameter or return types


// skipped function GetHolidaysByYear with unsupported parameter or return types


// skipped function GetHolidaysByYm with unsupported parameter or return types


// skipped function ListSolarFromBaZi with unsupported parameter or return types


// skipped function ListSolarFromBaZiBySect with unsupported parameter or return types


// skipped function ListSolarFromBaZiBySectAndBaseYear with unsupported parameter or return types


FOUNDATION_EXPORT CalendarDaYun* _Nullable CalendarNewDaYun(CalendarYun* _Nullable yun, long index);

FOUNDATION_EXPORT CalendarEightChar* _Nullable CalendarNewEightChar(CalendarLunar* _Nullable lunar);

// skipped function NewExactDateFromDate with unsupported parameter or return types


// skipped function NewExactDateFromYmd with unsupported parameter or return types


// skipped function NewExactDateFromYmdHms with unsupported parameter or return types


FOUNDATION_EXPORT CalendarFoto* _Nullable CalendarNewFoto(long year, long month, long day, long hour, long minute, long second);

FOUNDATION_EXPORT CalendarFotoFestival* _Nullable CalendarNewFotoFestival(NSString* _Nullable name, NSString* _Nullable result, BOOL everyMonth, NSString* _Nullable remark);

FOUNDATION_EXPORT CalendarFoto* _Nullable CalendarNewFotoFromLunar(CalendarLunar* _Nullable lunar);

FOUNDATION_EXPORT CalendarFoto* _Nullable CalendarNewFotoFromYmd(long year, long month, long day);

FOUNDATION_EXPORT CalendarFu* _Nullable CalendarNewFu(NSString* _Nullable name, long index);

FOUNDATION_EXPORT CalendarHoliday* _Nullable CalendarNewHoliday(NSString* _Nullable day, NSString* _Nullable name, BOOL work, NSString* _Nullable target);

FOUNDATION_EXPORT CalendarJieQi* _Nullable CalendarNewJieQi(NSString* _Nullable name, CalendarSolar* _Nullable solar);

FOUNDATION_EXPORT CalendarLiuNian* _Nullable CalendarNewLiuNian(CalendarDaYun* _Nullable daYun, long index);

FOUNDATION_EXPORT CalendarLiuYue* _Nullable CalendarNewLiuYue(CalendarLiuNian* _Nullable liuNian, long index);

FOUNDATION_EXPORT CalendarLunar* _Nullable CalendarNewLunar(long lunarYear, long lunarMonth, long lunarDay, long hour, long minute, long second);

// skipped function NewLunarFromDate with unsupported parameter or return types


FOUNDATION_EXPORT CalendarLunar* _Nullable CalendarNewLunarFromSolarYmd(long year, long month, long day, long hour, long minute, long second);

FOUNDATION_EXPORT CalendarLunar* _Nullable CalendarNewLunarFromYmd(long lunarYear, long lunarMonth, long lunarDay);

FOUNDATION_EXPORT CalendarLunarMonth* _Nullable CalendarNewLunarMonth(long lunarYear, long lunarMonth, long dayCount, double firstJulianDay);

FOUNDATION_EXPORT CalendarLunarMonth* _Nullable CalendarNewLunarMonthFromYm(long lunarYear, long lunarMonth);

FOUNDATION_EXPORT CalendarLunarTime* _Nullable CalendarNewLunarTime(long lunarYear, long lunarMonth, long lunarDay, long hour, long minute, long second);

FOUNDATION_EXPORT CalendarLunarYear* _Nullable CalendarNewLunarYear(long lunarYear);

FOUNDATION_EXPORT CalendarNineStar* _Nullable CalendarNewNineStar(long index);

FOUNDATION_EXPORT CalendarShuJiu* _Nullable CalendarNewShuJiu(NSString* _Nullable name, long index);

FOUNDATION_EXPORT CalendarSolar* _Nullable CalendarNewSolar(long year, long month, long day, long hour, long minute, long second);

// skipped function NewSolarFromDate with unsupported parameter or return types


FOUNDATION_EXPORT CalendarSolar* _Nullable CalendarNewSolarFromJulianDay(double julianDay);

FOUNDATION_EXPORT CalendarSolar* _Nullable CalendarNewSolarFromYmd(long year, long month, long day);

FOUNDATION_EXPORT CalendarSolarHalfYear* _Nullable CalendarNewSolarHalfYear(void);

// skipped function NewSolarHalfYearFromDate with unsupported parameter or return types


FOUNDATION_EXPORT CalendarSolarHalfYear* _Nullable CalendarNewSolarHalfYearFromYm(long year, long month);

FOUNDATION_EXPORT CalendarSolarMonth* _Nullable CalendarNewSolarMonth(void);

// skipped function NewSolarMonthFromDate with unsupported parameter or return types


FOUNDATION_EXPORT CalendarSolarMonth* _Nullable CalendarNewSolarMonthFromYm(long year, long month);

FOUNDATION_EXPORT CalendarSolarSeason* _Nullable CalendarNewSolarSeason(void);

// skipped function NewSolarSeasonFromDate with unsupported parameter or return types


FOUNDATION_EXPORT CalendarSolarSeason* _Nullable CalendarNewSolarSeasonFromYm(long year, long month);

FOUNDATION_EXPORT CalendarSolarWeek* _Nullable CalendarNewSolarWeek(long start);

// skipped function NewSolarWeekFromDate with unsupported parameter or return types


FOUNDATION_EXPORT CalendarSolarWeek* _Nullable CalendarNewSolarWeekFromYmd(long year, long month, long day, long start);

FOUNDATION_EXPORT CalendarSolarYear* _Nullable CalendarNewSolarYear(void);

// skipped function NewSolarYearFromDate with unsupported parameter or return types


FOUNDATION_EXPORT CalendarSolarYear* _Nullable CalendarNewSolarYearFromYear(long year);

FOUNDATION_EXPORT CalendarTao* _Nullable CalendarNewTao(long year, long month, long day, long hour, long minute, long second);

FOUNDATION_EXPORT CalendarTaoFestival* _Nullable CalendarNewTaoFestival(NSString* _Nullable name, NSString* _Nullable remark);

FOUNDATION_EXPORT CalendarTao* _Nullable CalendarNewTaoFromLunar(CalendarLunar* _Nullable lunar);

FOUNDATION_EXPORT CalendarTao* _Nullable CalendarNewTaoFromYmd(long year, long month, long day);

FOUNDATION_EXPORT CalendarXiaoYun* _Nullable CalendarNewXiaoYun(CalendarDaYun* _Nullable daYun, long index, BOOL forward);

FOUNDATION_EXPORT CalendarYun* _Nullable CalendarNewYun(CalendarEightChar* _Nullable eightChar, long gender);

#endif
